import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import StarsCanvas from "@/components/Hero/StarsBackground";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI for future of software engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="scroll-smooth">
      <head />
      <body className={`${spaceGrotesk.className} overflow-y-scroll overflow-x-hidden `}>
            <StarsCanvas />
            <Navbar />
            {children}
        </body>
    </html>
  );
}
